### ISSUE TITLE
`BUILD_UPDATE_DELAY` env var has no effect

### ISSUE THREAD

**Issue by filcuk** [shommey/dockerized-quartz#2]
It appears that the watch script uses `DELAY` instead of `BUILD_UPDATE_DELAY`:
https://github.com/shommey/dockerized-quartz/blob/313f7e8e76d41e20c300a63acd6e1d9f19900961/scripts/watch-and-build-quartz.sh#L9

The following rebuilds seconds after a change, instead of 5 minutes:
```
    environment:
      # GIT_REPO: "https://github.com/jackyzha0/quartz.git"
      # GIT_BRANCH: "main"
      BUILD_UPDATE_DELAY: 300
      DELAY: 3
      AUTO_REBUILD: true
```
